# Generated by Django 3.2.5 on 2022-06-15 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaPreguntaSecundarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_definirProb_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMCE.definirproblema')),
            ],
        ),
        migrations.DeleteModel(
            name='EvaluacionPreguntaSecundarias',
        ),
    ]
