# Generated by Django 3.2.5 on 2022-07-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0002_auto_20220614_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participacionest',
            old_name='contentido',
            new_name='contenido',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='preguntas_secundarias',
        ),
        migrations.AddField(
            model_name='definirproblema',
            name='retro_inicial',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='definirproblema',
            name='retro_secundarias',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60, verbose_name='Título')),
                ('autor', models.CharField(max_length=60, verbose_name='Autor')),
                ('fecha_publicacion', models.CharField(max_length=10, verbose_name='Fecha de Publicación')),
                ('lugar', models.CharField(max_length=60, verbose_name='Lugar de Publicación')),
                ('tipo_fuente', models.CharField(choices=[('0', 'LIBRO'), ('1', 'REVISTA'), ('2', 'PERIODICO'), ('3', 'SITIO WEB'), ('4', 'VIDEO'), ('5', 'IMAGEN')], max_length=1, verbose_name='Tipo de Fuente')),
                ('tipo_recurso', models.CharField(choices=[('0', 'ARCHIVO'), ('1', 'ENLACE')], max_length=1, verbose_name='Tipo de Recurso')),
                ('enlace', models.CharField(max_length=120, verbose_name='Enlace')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMCE.estudiante')),
            ],
        ),
    ]
