# Generated by Django 3.2.5 on 2022-07-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0003_auto_20220713_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuente',
            name='autor',
            field=models.CharField(max_length=60, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='fuente',
            name='fecha_publicacion',
            field=models.CharField(max_length=10, null=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='fuente',
            name='lugar',
            field=models.CharField(max_length=60, null=True, verbose_name='Lugar de Publicación'),
        ),
    ]
