# Generated by Django 3.2.5 on 2022-07-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0004_auto_20220713_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente',
            name='definirProb_fuentes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AMCE.definirproblema'),
        ),
    ]
