# Generated by Django 3.2.9 on 2022-08-03 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0006_auto_20220728_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuentesSeleccionadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_defproblema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definirproblema', to='AMCE.definirproblema')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='AMCE.estudiante')),
                ('id_fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuente', to='AMCE.fuente')),
            ],
        ),
    ]
