# Generated by Django 3.2.9 on 2022-08-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0007_fuentesseleccionadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuente',
            name='definirProb_fuentes_id',
        ),
        migrations.RemoveField(
            model_name='fuente',
            name='estudiante',
        ),
    ]
