# Generated by Django 3.2.9 on 2022-08-03 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0008_auto_20220802_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente',
            name='definirProb_fuentes_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AMCE.definirproblema'),
        ),
    ]
