# Generated by Django 3.2.9 on 2022-08-03 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0009_fuente_definirprob_fuentes_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuente',
            old_name='definirProb_fuentes_id',
            new_name='id_defproblema',
        ),
    ]
