# Generated by Django 3.2.9 on 2022-08-04 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0012_auto_20220803_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentariospreguntainicial',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='comentariospreguntainicial',
            name='id_defproblema',
        ),
        migrations.RemoveField(
            model_name='comentariospreguntainicial',
            name='id_estudiante',
        ),
        migrations.RemoveField(
            model_name='comentariospreguntainicial',
            name='id_fuente',
        ),
        migrations.AddField(
            model_name='comentariospreguntainicial',
            name='participacionEst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AMCE.participacionest'),
        ),
        migrations.AddField(
            model_name='comentariospreguntainicial',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AMCE.pregunta'),
        ),
        migrations.CreateModel(
            name='EvaluacionFuentesSel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(null=True)),
                ('id_defproblema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definirproblemaEvFuente', to='AMCE.definirproblema')),
                ('id_estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudianteEvFuente', to='AMCE.estudiante')),
                ('id_fuente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AMCE.fuente')),
            ],
        ),
    ]
