# Generated by Django 3.2.9 on 2022-08-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0013_auto_20220803_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='paso',
        ),
        migrations.AddField(
            model_name='definirproblema',
            name='paso',
            field=models.IntegerField(default=1),
        ),
    ]
